name: plasmid-ai
channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchtriton=2.1
  - cuda=11.8
  - packaging
  - ninja
  - cxx-compiler
  - gxx=11
  - lightning
  - wandb
  - pydantic<2
  - pydantic-cli
  - einops
  - scipy
  - gdown
  - pandas
  - biopython
  - mmseqs2
  - pip
  - pip:
    - mamba-ssm     
